[tool.poetry]
name = "lesson-03"
version = "0.1.0"
description = ""
authors = ["sherman"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
